# From 'openshift-applier'
- src: https://github.com/redhat-cop/openshift-applier
  version: v2.1.2
# From 'openshift-labels'
- src: https://github.com/redhat-cop/casl-ansible.git
  version: v3.11.4

# Get the roles under development
- src: https://github.com/westdart/ar_osc_amqbroker.git
  version: v1.2

# Get the roles under development
- src: https://github.com/westdart/ar_osc_amqinterconnect.git
  version: v1.0

# Get the roles under development
- src: https://github.com/westdart/ar_osc_aspera.git
  version: v1.1

# Get the roles under development
- src: https://github.com/westdart/ar_os_scc_binding.git
  version: v1.0

# Get the roles under development
- src: https://github.com/westdart/ar_tls_ca.git
  version: v1.0

# Get the roles under development
- src: https://github.com/westdart/ar_osc_common_templates.git
  version: v1.1
