---
- name: Add users to groups
  hosts: localhost

  vars:
    group: 'testgroup'
    users:
      - testuser
      - admin

  tasks:
    - name: Include ar_os_group_users for {{ group }}
      include_role:
        name: ar_os_group_users
      vars:
        ar_os_group_users_group_name: "{{ group }}"
        ar_os_group_users_members:    "{{ users }}"
